
create database customer_behavior;
USE customer_behavior;
create table customer;
select*from customer;

# What is the total revenue generated by male vs female customer
select gender,SUM(purchase_amount) as revenue
from customer
group by gender;

#Which customer used a discount but still spent more than the average purchase amount
select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>=( select AVG(purchase_amount) from customer);

#Which are the top 5 products with the highest review rating
select item_purchased, round(AVG(review_rating ),2)  as 'Average product rating'
from customer 
group by item_purchased
order by Avg(review_rating) desc
limit 5;

#Compare the average purchase amount between standard & express shipping
select shipping_type ,ROUND(AVG(purchase_amount),1)
from customer
where shipping_type in ('standard','Express')
group by shipping_type;

#Do subscribed customers spend more? compare avg Spend and total revenue between subscribeds and non subscribers
select subscription_status,
count(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue 
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

# Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100*SUM(case when discount_applied='Yes' Then 1 Else 0 END)/COUNT(*),2)
as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

#Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;CT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

#What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

#Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

#What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

 

